version: '3.4'

services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      FLASK_DEBUG: 'true'
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - '6379:6379'
