version: "3"
services:
  api:
    build: ./api
    environment:
      PORT: 5000
    ports:
      - 5000:5000
    networks:
        - vnet1
    depends_on:
      - redis
  redis-db:
    image: redis
    ports: 
      - 6379:6379
    networks:
      - vnet1
networks:
  vnet1:
    driver: bridge 
