version: '3.8'

services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"